package gym.domain;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

import java.util.Date;
import java.util.List;
import java.util.UUID;

public class DomainObjectsTest {

    @Test
    public void testUserGettersAndToString() {
        User u = new User("First","Last","user123","pass",true);
        Assertions.assertEquals("First", u.getFirstName());
        Assertions.assertEquals("Last", u.getLastName());
        Assertions.assertEquals("user123", u.getUsername());
        Assertions.assertTrue(u.isActive());
        String s = u.toString();
        Assertions.assertTrue(s.contains("First"));
        Assertions.assertTrue(s.contains("Last"));
        Assertions.assertTrue(s.contains("user123"));
    }

    @Test
    public void testTraineeGettersAndToString() {
        Date dob = new Date(1000L);
        Trainee t = new Trainee(new User("TFirst","TLast","tuser","tpw",false), dob, "addr");
        Assertions.assertEquals(dob, t.getDateOfBirth());
        Assertions.assertEquals("addr", t.getAddress());
        // Id is generated by JPA; ensure user reference is correct
        Assertions.assertEquals("tuser", t.getUser().getUsername());
        String s = t.toString();
        Assertions.assertTrue(s.contains("TFirst"));
        Assertions.assertTrue(s.contains("addr"));
        Assertions.assertTrue(s.contains("tuser"));
    }

    @Test
    public void testTrainerGettersAndToString() {
        Trainer tr = new Trainer(new User("TrFirst","TrLast","truser","trpw",true), List.of());
        Assertions.assertEquals("truser", tr.getUser().getUsername());
        // specialization list empty in this test
        String s = tr.toString();
        Assertions.assertTrue(s.contains("TrFirst"));
        Assertions.assertTrue(s.contains("truser"));
    }

    @Test
    public void testTrainingGettersAndToString() {
        Date date = new Date(2000L);
        TrainingType type = new TrainingType("cardio");
        Trainee trainee = new Trainee(new User("A","B","tuser","p",true), null, null);
        Trainer trainer = new Trainer(new User("C","D","truser","p",true), List.of());
        Training tr = new Training(trainee, trainer, "Run", type, date, 30);
        Assertions.assertEquals("Run", tr.getTrainingName());
        Assertions.assertEquals(type, tr.getTrainingType());
        Assertions.assertEquals(date, tr.getTrainingDate());
        Assertions.assertEquals(30, tr.getTrainingDuration());
        String s = tr.toString();
        Assertions.assertTrue(s.contains("Run"));
        Assertions.assertTrue(s.contains("cardio"));
        Assertions.assertTrue(s.contains("tuser"));
    }

    @Test
    public void testTrainingTypeGettersAndToString() {
        TrainingType tt = new TrainingType("yoga");
        Assertions.assertEquals("yoga", tt.getTrainingTypeName());
        String s = tt.toString();
        Assertions.assertTrue(s.contains("yoga"));
    }
}
